### PR TITLE
Add task that reinstalls the jar when files change

### PR DESCRIPTION
**Pull request by bhagany**
I find a task like this to be very useful when working on libraries

### CODE REVIEW

**Comment by samestep** [comment]
Would it work better to instead put this task in [`profile.boot`][wiki], and perhaps add a `.gitignore` to this repository that accounts for the `profile.boot` file?

[wiki]: https://github.com/boot-clj/boot/wiki/Configuring-Boot#configuring-your-clojure-project

**Comment by bhagany** [comment]
I suppose, I just think it's nice for libraries to provide this sort of thing themselves, so that everybody has an easy way to hack on them without having to do much else.  I got the idea from other libraries that do this, like https://github.com/hashobject/perun/blob/master/build.boot#L42 and https://github.com/adzerk-oss/boot-reload/blob/master/build.boot#L27

**Comment by samestep** [comment]
That makes sense. Could you adjust the indentation of your usage of `comp` to follow the [community style guide][style] and add a brief section to the `README` that mentions the `dev` task and demonstrates its usage?

[style]: https://github.com/bbatsov/clojure-style-guide#one-space-indent

**Comment by bhagany** [comment]
Sure, done.  Let me know if you'd like to see any other changes.

**Comment by samestep** [comment]
Looks good, thanks!

**Pull request merged**
